#!/bin/bash
CONTENT_FILE=/tmp/content
SECRET=/etc/2fa/secret
ADDRESSES=( '[2001:db8::1]' '192.0.0.1' )
export PATH="/usr/local/bin:/bin:/usr/bin"

cp -a $SECRET $CONTENT_FILE
mkdir -p /usr/local/etc/oath/

while true; do 
  socat TCP6-LISTEN:165,bind=::1,reuseaddr OPEN:/dev/null || sleep 10
  for file in $(find /home/ -iname .oath.enc); do
    user=$(stat -c %U $file)
    echo Sending credentials for "$user"
    cat $file > $CONTENT_FILE
    echo $user >> $CONTENT_FILE
    cat $SECRET $CONTENT_FILE | openssl sha3-256 -binary | base64 >> $CONTENT_FILE
    for ADDRESS in "${ADDRESSES[@]}"
      do if socat OPEN:$CONTENT_FILE TCP-CONNECT:$ADDRESS:165,connect-timeout=100
        then SEND=OK
        else echo Can not send $user to $ADDRESS >&2
        fi
    done
    test -n "$SEND" && mv $file /usr/local/etc/oath/$user
  done
done
